# Generated by Django 5.2.8 on 2025-11-05 23:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_hora', models.DateTimeField()),
                ('distancia_km', models.FloatField(default=5.0)),
                ('categoria', models.CharField(choices=[('estudiantes', 'Estudiantes por Equipos'), ('interfacultades', 'Interfacultades por Equipos')], max_length=20)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Juez',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jueces', to='app.competencia')),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('dorsal', models.IntegerField()),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='app.competencia')),
                ('juez_asignado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos_asignados', to='app.juez')),
            ],
            options={
                'ordering': ['dorsal'],
                'unique_together': {('competencia', 'dorsal')},
            },
        ),
        migrations.CreateModel(
            name='RegistroTiempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_registro', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tiempo', models.BigIntegerField(help_text='Tiempo en milisegundos')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiempos', to='app.equipo')),
                ('juez', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='app.juez')),
            ],
            options={
                'ordering': ['tiempo'],
                'indexes': [models.Index(fields=['equipo', 'tiempo'], name='app_registr_equipo__234598_idx')],
            },
        ),
    ]
