# Generated by Django 5.2.8 on 2025-11-05 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrotiempo',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='registrotiempo',
            name='app_registr_equipo__234598_idx',
        ),
        migrations.RemoveField(
            model_name='competencia',
            name='distancia_km',
        ),
        migrations.AlterUniqueTogether(
            name='equipo',
            unique_together={('juez_asignado', 'dorsal')},
        ),
        migrations.RemoveField(
            model_name='registrotiempo',
            name='juez',
        ),
        migrations.AlterField(
            model_name='equipo',
            name='juez_asignado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos_asignados', to='app.juez'),
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='competencia',
        ),
    ]
