# Generated by Django 5.2.8 on 2025-11-05 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_registrotiempo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrotiempo',
            options={'ordering': ['tiempo']},
        ),
        migrations.AddIndex(
            model_name='registrotiempo',
            index=models.Index(fields=['equipo', 'tiempo'], name='app_registr_equipo__234598_idx'),
        ),
    ]
