# Generated by Django 5.2.8 on 2025-11-06 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_registrotiempo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competencia',
            options={'verbose_name': 'Competencia', 'verbose_name_plural': 'Competencias'},
        ),
        migrations.AddField(
            model_name='competencia',
            name='en_curso',
            field=models.BooleanField(default=False, verbose_name='En curso'),
        ),
        migrations.AddField(
            model_name='competencia',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de finalización'),
        ),
        migrations.AddField(
            model_name='competencia',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de inicio'),
        ),
    ]
